font = 'Adwaita Mono:size=14'
letter-spacing = 1
dpi-aware = auto
prompt = ">  "
icons-enabled = no
match-mode = fuzzy
filter-desktop = yes
# output=<not set>
# fields=filename,name,generic
# layer = top
# anchor = center
# x-margin = 7
# y-margin = 7

lines = 10
width = 40
horizontal-pad = 20
vertical-pad = 10
inner-pad = 10
exit-on-keyboard-focus-loss = no

# to get transparency change last 2 chars: 00 is transparent and ff is opaque.
[colors]
prompt = 4294abff
background = 181818ff
text = f8f8f8ff
match = f8f8f8ff
selection-match = f8f8f8ff
selection = 4294abff
selection-text = f8f8f8ff
border = 4294abff

[border]
width = 2
radius = 7
